#!/bin/bash

# install <(curl 'http://devtools.qiniu.com/2.1.3/qshell-linux-x64') /usr/local/bin/qshell
# <(curl 'https://bce.bdstatic.com/bce-bos-uploader-lite/1.0.4/bce-bos-uploader-lite.min.js')\
# npm install uglify-js -g
#./js/bce-bos-uploader-lite.js\
#./js/ybuploader.js\
#./js/ybuploader_1126.js\
# ./js/CosMultipartUpload.js\
# ./js/xml2json.js\
# ./js/webuploader.js\

cat ./js/hmac_sha1.js\
    ./js/bce-bos-uploader-lite.js\
    ./js/raven.min.js\
    ./js/jquery.ajax-retry.js\
    ./webuploader/dist/webuploader.html5only.js\
    ./js/ybuploader.js\
    |grep -v "input\.attr( 'capture', 'camera');" \
    > ./js/ybuploader.full.js
echo build

if [ x$1 = xdeploy ];then

    qshell fput bvcstatic uploadlab/js/ybuploader.full.js ./js/ybuploader.full.js true &&\
    qshell cdnrefresh <(echo http://bvcstatic.acgvideo.com/uploadlab/js/ybuploader.full.js) &&\
    echo //bvcstatic.acgvideo.com/uploadlab/js/ybuploader.full.js?_=$(date|md5sum|head -c8)

    echo 'Deploy!!! Are you sure?'
    read a
    test ! x${a} = xyes && exit 1

    version=$(($(cat ./version) + 1))
    echo $version > ./version
    echo $version 
    DATEVERSION=$version-$(date +%y%m%d%H%M)

    echo mining &&\
    uglifyjs ./js/ybuploader.full.js -c > ./js/ybuploader.full.min.js &&\
    echo fput &&\
    qshell fput bvcstatic uploadlab/js/ybuploader${DATEVERSION}.full.min.js  ./js/ybuploader.full.min.js true &&\
    qshell cdnrefresh <(echo http://bvcstatic.acgvideo.com/uploadlab/js/ybuploader${DATEVERSION}.full.min.js) &&\
    echo http://bvcstatic.acgvideo.com/uploadlab/js/ybuploader${DATEVERSION}.full.min.js
    curl -I http://bvcstatic.acgvideo.com/uploadlab/js/ybuploader${DATEVERSION}.full.min.js|grep -i Content-Length
fi
